import { resetCookingInfos } from "@stores/features/cookingInfos";
import { resetCookingUstensils } from "@stores/features/cookingUstensils";
import { resetIngredientCategories } from "@stores/features/ingredientCategories";
import { resetIngredients } from "@stores/features/ingredients";
import { resetManualAdjustements } from "@stores/features/manualAdjustements";
import { resetProducts } from "@stores/features/products";
import { resetRecipeCategories } from "@stores/features/recipeCategories";
import { resetRecipes } from "@stores/features/recipes";
import { resetSeeds } from "@stores/features/seeds";
import { resetShoppingList } from "@stores/features/shoppingList";
import { resetStorageInfos } from "@stores/features/storageInfos";
import { resetUnits } from "@stores/features/units";
import { resetWeeklyMenu } from "@stores/features/weeklyMenu";
import { AppDispatch } from "@stores/index";

export const resetReduxStore = (dispatch: AppDispatch) => {
  dispatch(resetCookingInfos());
  dispatch(resetCookingUstensils());
  dispatch(resetIngredientCategories());
  dispatch(resetIngredients());
  dispatch(resetProducts());
  dispatch(resetRecipeCategories());
  dispatch(resetRecipes());
  dispatch(resetSeeds());
  dispatch(resetManualAdjustements());
  dispatch(resetShoppingList());
  dispatch(resetStorageInfos());
  dispatch(resetUnits());
  dispatch(resetWeeklyMenu());
};
